apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
  namespace: spring-boot
  labels:
    app: helloworld
spec:
  type: NodePort
  selector:
    app: helloworld
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30009
